version: '3'

services:
  web:
    build: .
    environment:
      - BUNDLE_PATH=/bundle
    volumes:
      - bundle_path:/bundle
      - .:/app
    command: bundle exec ruby app.rb

volumes:
  bundle_path:
